-- Fergana NOW MVP 1.0
-- Безопасная идемпотентная миграция: можно запускать повторно.

-- 1) Двуязычные поля и обложка.
alter table public.places
  add column if not exists name_uz text,
  add column if not exists description_uz text,
  add column if not exists address_uz text,
  add column if not exists image_url text;

alter table public.events
  add column if not exists title_uz text,
  add column if not exists description_uz text;

alter table public.offers
  add column if not exists title_uz text,
  add column if not exists description_uz text;

-- 2) Избранное и история для optional Supabase anonymous-auth sync.
create table if not exists public.user_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  place_id bigint not null references public.places(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, place_id)
);

create table if not exists public.user_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  place_id bigint not null references public.places(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  unique (user_id, place_id)
);

alter table public.user_favorites enable row level security;
alter table public.user_history enable row level security;

drop policy if exists "favorites_select_own" on public.user_favorites;
create policy "favorites_select_own"
on public.user_favorites for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "favorites_insert_own" on public.user_favorites;
create policy "favorites_insert_own"
on public.user_favorites for insert
to authenticated
with check (auth.uid() = user_id);


drop policy if exists "favorites_update_own" on public.user_favorites;
create policy "favorites_update_own"
on public.user_favorites for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "favorites_delete_own" on public.user_favorites;
create policy "favorites_delete_own"
on public.user_favorites for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "history_select_own" on public.user_history;
create policy "history_select_own"
on public.user_history for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "history_insert_own" on public.user_history;
create policy "history_insert_own"
on public.user_history for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "history_update_own" on public.user_history;
create policy "history_update_own"
on public.user_history for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

grant select, insert, update, delete on public.user_favorites to authenticated;
grant select, insert, update on public.user_history to authenticated;

-- 3) Public bucket rasmlar. Если bucket уже есть, просто делаем его public.
insert into storage.buckets (id, name, public)
values ('rasmlar', 'rasmlar', true)
on conflict (id) do update set public = true;

-- Чтение фотографий public bucket не требует object SELECT policy.
-- Загрузка фотографий по-прежнему выполняется из Supabase Dashboard.
